# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Cortrah
  admin_email: cort@cortwinters.net
  admin_password: octofish
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: cortwinter.net
  secret_key_base: 7ad67119f5137ee848fb9ed5b3a8aaa530b3723543014459452956d7a57ea6b46e42c283b62e2629be96c106c838dff155c2be4ec188456223e65a488402dee5

test:
  domain_name: example.com 
  secret_key_base: 5d5b7e5c797a4b158c0d141b7237899da7a2dc200d15ecbe2fac3c8bca039b806ca1afd9dfdcfa41565a1e005dc63695aa52087bb140ba07131cde736bed2e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
